import React, { useCallback, useState } from "react";
import { Alert, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useFocusEffect } from "expo-router";
import { api, formatApiError } from "../../src/api";

const EVENTS = ["proposal.created", "proposal.accepted", "bling.sales_order.created"];

export default function Webhooks() {
  const [url, setUrl] = useState("");
  const [events, setEvents] = useState<string[]>(["proposal.accepted"]);
  const [hooks, setHooks] = useState<any[]>([]);
  const [deliveries, setDeliveries] = useState<any[]>([]);
  const [saving, setSaving] = useState(false);
  const load = async () => { const [webhooks, history] = await Promise.all([api.get("/webhooks"), api.get("/webhooks/deliveries")]); setHooks(webhooks.data || []); setDeliveries(history.data || []); };
  useFocusEffect(useCallback(() => { load().catch(() => {}); }, []));
  const create = async () => { if (saving) return; try { setSaving(true); const { data } = await api.post("/webhooks", { url, events }); setUrl(""); await load(); Alert.alert("Webhook criado", `Copie e guarde este segredo agora. Ele não será exibido novamente:\n\n${data.secret}`); } catch (error) { Alert.alert("Não foi possível salvar", formatApiError(error)); } finally { setSaving(false); } };
  const toggle = async (hook: any) => { try { await api.patch(`/webhooks/${hook.id}`, { enabled: !hook.enabled }); await load(); } catch (error) { Alert.alert("Não foi possível atualizar", formatApiError(error)); } };
  const rotateSecret = async (hook: any) => { try { const { data } = await api.post(`/webhooks/${hook.id}/secret`); Alert.alert("Novo segredo", `Copie e substitua o segredo no n8n agora. O anterior deixa de funcionar:\n\n${data.secret}`); } catch (error) { Alert.alert("Não foi possível gerar o segredo", formatApiError(error)); } };
  const retry = async (delivery: any) => { try { await api.post(`/webhooks/deliveries/${delivery.id}/retry`); await load(); } catch (error) { Alert.alert("Não foi possível reenviar", formatApiError(error)); } };
  return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>Webhooks</Text><Text style={s.sub}>Envie eventos assinados para o n8n. O segredo é mostrado somente na criação.</Text><View style={s.card}><Text style={s.label}>URL do webhook n8n</Text><TextInput value={url} onChangeText={setUrl} placeholder="https://seu-n8n/webhook/proposta" autoCapitalize="none" autoCorrect={false} keyboardType="url" style={s.input}/><Text style={s.label}>Eventos</Text>{EVENTS.map(event => <TouchableOpacity key={event} onPress={() => setEvents(v => v.includes(event) ? v.filter(x => x !== event) : [...v, event])}><Text style={s.event}>{events.includes(event) ? "☑" : "☐"} {event}</Text></TouchableOpacity>)}<TouchableOpacity style={[s.button, saving && s.disabled]} disabled={saving} onPress={create}><Text style={s.buttonText}>{saving ? "Salvando..." : "Criar webhook"}</Text></TouchableOpacity></View><Text style={s.heading}>Webhooks ativos</Text>{hooks.length === 0 ? <Text style={s.muted}>Nenhum webhook configurado.</Text> : hooks.map(h => <View style={s.card} key={h.id}><Text numberOfLines={1}>{h.url}</Text><Text style={s.muted}>{h.events.join(" · ")}</Text><View style={s.row}><Text>{h.enabled ? "Ativo" : "Pausado"}</Text><Switch value={h.enabled} onValueChange={() => toggle(h)}/></View><TouchableOpacity style={s.secondaryButton} onPress={() => rotateSecret(h)}><Text style={s.secondaryButtonText}>Gerar novo segredo</Text></TouchableOpacity></View>)}<Text style={s.heading}>Últimas entregas</Text>{deliveries.length === 0 ? <Text style={s.muted}>Os envios aparecerão aqui.</Text> : deliveries.map(d => <View style={s.delivery} key={d.id}><View><Text style={s.deliveryEvent}>{d.event}</Text><Text style={s.muted}>{d.status}{d.response_status ? ` · HTTP ${d.response_status}` : ""}{d.attempts ? ` · ${d.attempts} tentativa(s)` : ""}</Text></View>{d.status === "FAILED" && <TouchableOpacity style={s.retry} onPress={() => retry(d)}><Text style={s.retryText}>Reenviar</Text></TouchableOpacity>}</View>)}</ScrollView>;
}
const s=StyleSheet.create({page:{padding:24,gap:12},title:{fontSize:28,fontWeight:"800"},sub:{color:"#64748B"},card:{borderWidth:1,borderColor:"#E2E8F0",borderRadius:14,padding:16,gap:10},label:{fontWeight:"700"},input:{borderWidth:1,borderColor:"#CBD5E1",borderRadius:8,padding:12},event:{paddingVertical:6},button:{backgroundColor:"#0F766E",padding:14,borderRadius:8,alignItems:"center"},buttonText:{color:"white",fontWeight:"700"},secondaryButton:{borderWidth:1,borderColor:"#0F766E",padding:12,borderRadius:8,alignItems:"center"},secondaryButtonText:{color:"#0F766E",fontWeight:"700"},disabled:{opacity:0.55},heading:{fontSize:18,fontWeight:"800",marginTop:8},muted:{color:"#64748B"},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},delivery:{borderBottomWidth:1,borderColor:"#E2E8F0",paddingVertical:10,flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:12},deliveryEvent:{fontWeight:"700"},retry:{borderWidth:1,borderColor:"#0F766E",borderRadius:7,paddingHorizontal:10,paddingVertical:7},retryText:{color:"#0F766E",fontWeight:"700"}});
